### PR TITLE
HttpClient life-cycle management. 

### PR DESCRIPTION
**Pull request by serjkazhura**
Hi guys,
we recently had a problem with the sdk. After some investigation we figured out that the problem was - using too many HttpClients. If you are running on high throughput - the application is choking. We are running our code in Azure Functions on consumption plan, it is limited to 300 http connections. We reached the limit pretty quickly unfortunately. 
There is an anti-pattern  described [here](https://docs.microsoft.com/en-us/azure/architecture/antipatterns/improper-instantiation). 
I left everything as is, just added a possibility to use our own `HttpClient` factory. This way we can create a singleton `HttpClient` in our code and dispose it on `Application End`. I've added a default implementation of `TransientHttpClientFactory` to mimic the existing behavior, so nothing will break for any other consumers. All the test are passing as well. 
Thanks in advance!

### CODE REVIEW

**Comment by bezysoftware** [comment]
Thx for the contribution, I'm away this week, I'll take a look when I get back

**Comment by serjkazhura** [comment]
Sounds good, thank you!

**Comment by bezysoftware** [comment]
I think this needs more work. The RealtimeDabase piece of the lib (facilitating offline capabilities) relies on the SetHandler, which does puts & patches: https://github.com/step-up-labs/firebase-database-dotnet/blob/master/src/Firebase/Offline/SetHandler.cs

As you can see in the code, this uses a using statement, which ends with calling the dispose method of the new FirebaseQuery: https://github.com/step-up-labs/firebase-database-dotnet/blob/master/src/Firebase/Query/FirebaseQuery.cs#L236
which disposes the HttpClient. 

This was done to address the issue you mention - RealtimeDatabase would over time create so many FirebaseQueries (each with new HttpClient) it would make the host app choke. Disposing it solves the issue - but disposing the only 1 instance of HttpClient would break things.

Therefore there must be a mechanism to not dispose the HttpClient. I suggest adding another method to the HttpClientFactory, e.g. Dispose(HttpClient client). In the TransientHttpClientFactory, it would simply dispose it, in any other implementation, it would be up to the author (e.g. do nothing). 

What do you think?

**Comment by serjkazhura** [comment]
Good catch! 
I haven't noticed the  [SetHandler](https://github.com/step-up-labs/firebase-database-dotnet/blob/master/src/Firebase/Offline/SetHandler.cs) for some reason. 
What if `HttpClientFactory` will return an `IHttpClientProxy` instead of `HttpClient`. Something like this:
```
public interface IHttpClientProxy : IDisposable 
{
    HttpClient GetCleint();
}
```
The default implementation  will just encapsulate an instance of the `HttpClient` and will be used in `FirebaseQuery` (via the interface of course) instead of a direct reference to an `HttpClient`. 
Now it will be possible to create your own `IHttpClientFactory` with your own implementation of `IHttpCleintProxy` where you will be in charge of the disposal mechanism. 
Static implementation will pretty much do nothing on dispose, but rather hold an instance of the `HttpClient`  and you will be able to safely dispose it on `Application_End` event. 

How does this sound?

**Comment by bezysoftware** [comment]
Sounds good!

**Comment by serjkazhura** [comment]
I will try to implement the changes ASAP. Thanks!

**Comment by serjkazhura** [comment]
Hi, Tomas! I've implemented all the suggested changes. Please review. Thanks!

**Comment by bezysoftware** [comment]
Thanks! Deployed to nuget in beta4

**Pull request merged**
